; mini-Scheme 自查程序（值层面，自动判定）。
; 约定：check 通过时不打印任何东西，失败时打印一行 "FAIL ..."。
; 因此**期望输出只有最后一行 "selftest done"**；出现任何 FAIL 行即为不通过。
; 这里刻意用 mini-Scheme 自己写 check，顺带把 define/lambda/if/cond/递归都跑一遍。

; check 只在失败时打印一行 "FAIL ..."；通过时走「省略假分支的 if」，
; 结果是「无值」，顶层不会打印任何东西（spec §4.2、§2）。
(define (check label got want)
  (if (not (equal? got want))
      (begin
        (display "FAIL ")
        (display label)
        (display ": got ")
        (display got)
        (display " want ")
        (display want)
        (newline))))

; ---------- §5 算术 ----------
(check "+var"     (+ 1 2 3) 6)
(check "+zero"    (+) 0)
(check "-var"     (- 10 4 1) 5)
(check "-neg"     (- 5) -5)
(check "*var"     (* 2 3 4) 24)
(check "*one"     (*) 1)
(check "/int"     (/ 7 2) 3)
(check "/neg1"    (/ -7 2) -3)
(check "/neg2"    (/ 7 -2) -3)
(check "/neg3"    (/ -7 -2) 3)
(check "/recip"   (/ 2) 0.5)
(check "/chain"   (/ 100 5 2) 10)
(check "/exact"   (/ 6 3) 2)
(check "mod"      (modulo 17 5) 2)
(check "mod-neg"  (modulo -17 5) 3)
(check "quo"      (quotient 17 5) 3)
(check "quo-neg"  (quotient -7 2) -3)
(check "expt"     (expt 2 10) 1024)
(check "expt0"    (expt 3 0) 1)
(check "expt-neg" (expt 2 -1) 0.5)
(check "abs"      (abs (- 5 9)) 4)
(check "abs2"     (abs -3) 3)

; ---------- §5 比较（链式 / 单项 / 数字与符号）----------
(check "=1"    (= 1 1) #t)
(check "=float" (= 1 1.0) #t)
(check "=bool" (= #t #t) #t)
(check "=bt1"  (= #t 1) #f)
(check "<chain" (< 2 3 4) #t)
(check "<fail" (< 2 3 3) #f)
(check ">eq"   (> 5 5) #f)
(check "<=ch"  (<= 1 1 2) #t)
(check ">=ch"  (>= 3 3 2) #t)
(check "<one"  (< 5) #t)
(check "=sym"  (= 'a 'a) #t)
(check "=sym2" (= 'a 'b) #f)
(check "<sym"  (< 'a 'b) #t)
(check "=str"  (= "x" "x") #t)

; ---------- §4.4 短路与真值 ----------
(check "and-short" (and #f (/ 1 0)) #f)
(check "or-short"  (or #t (/ 1 0)) #t)
(check "and-empty" (and) #t)
(check "or-empty"  (or) #f)
(check "and-last"  (and 1 2 3) 3)
(check "or-first"  (or #f #f 7) 7)
(check "or-allf"   (or #f #f) #f)
(check "not-0"     (not 0) #f)
(check "not-nil"   (not '()) #f)
(check "not-f"     (not #f) #t)
(check "not-5"     (not 5) #f)
(check "if-0"      (if 0 'truthy 'falsy) 'truthy)
(check "if-nil"    (if '() 'truthy 'falsy) 'truthy)
(check "if-str"    (if "" 'truthy 'falsy) 'truthy)

; ---------- §4.1 quote ----------
(check "quote-sym"  (quote x) 'x)
(check "quote-list" '(1 2 3) (list 1 2 3))
(check "quote-nil"  '() (list))
(check "quote-nest" '(1 (2 3) 4) (list 1 (list 2 3) 4))
(check "quote-dbl"  ''z (list 'quote 'z))
(check "car-q"      (car '(1 2 3)) 1)

; ---------- §4.3 cond ----------
(check "cond-mid"   (cond ((= 1 2) 'a) ((= 2 2) 'b) (else 'c)) 'b)
(check "cond-else"  (cond (else 'd)) 'd)
(check "cond-test"  (cond ((> 2 3)) (else 42)) 42)
(check "cond-truth" (cond (#f 'a) (5 'e)) 'e)
(check "cond-begin" (cond ((and #t #t) (begin 1 2))) 2)
(check "cond-none"  (list (cond ((= 1 2) 'a))) (list (if #f 1)))

; ---------- §4.5/§4.6 define / lambda ----------
(define pi 3)
(check "define-val" (+ pi 1) 4)
(define (square x) (* x x))
(check "define-fn"  (square 7) 49)
(define redefined 1)
(define redefined 2)
(check "redefine"   redefined 2)
(check "iife"       ((lambda (x) (* x 2)) 5) 10)
(check "lambda-def" ((lambda (a b) (+ a b)) 3 4) 7)
(check "zero-arg"   ((lambda () 9)) 9)

; ---------- §9 词法作用域与闭包 ----------
(define (make-adder n) (lambda (x) (+ x n)))
(define add5 (make-adder 5))
(check "closure-1"  (add5 10) 15)
(check "closure-2"  ((make-adder 100) 7) 107)
(define (outer-scope v)
  (define (inner x) (* x v))   ; 函数体内 define，且能看见外层参数 v
  (inner 3))
(check "inner-define" (outer-scope 4) 12)
(check "shadow"       (let ((x 1)) ((lambda (x) x) 99)) 99)

; ---------- §4.7 let：并行绑定 ----------
(check "let-basic"  (let ((x 3) (y 4)) (+ x y)) 7)
(check "let-nested" (let ((a 1)) (let ((b (+ a 1))) (* a b))) 2)
(check "let-par"    (let ((a 1)) (let ((a 5) (b a)) (list a b))) (list 5 1))
(check "let-body"   (let ((a 1)) (define b 2) (+ a b)) 3)

; ---------- §4.8 begin ----------
(check "begin-last" (begin 1 2 3) 3)
(define begin-z 0)
(check "begin-def"  (begin (define begin-z 1) (+ begin-z 41)) 42)

; ---------- §6 列表与点对 ----------
(check "cdr"        (cdr '(1 2 3)) '(2 3))
(check "cons-list"  (cons 1 '(2 3)) '(1 2 3))
(check "cons-pair"  (cons 1 2) (cons 1 2))
(check "cons-nest"  (cons '(1) '(2)) '((1) 2))
(check "list3"      (list 1 2 3) '(1 2 3))
(check "list0"      (list) '())
(check "length4"    (length '(a b c d)) 4)
(check "length0"    (length '()) 0)
(check "append"     (append '(1 2) '(3 4)) '(1 2 3 4))
(check "append-nil" (append '() '(1)) '(1))
(check "append3"    (append '(1) '() '(2)) '(1 2))
(check "null-t"     (null? '()) #t)
(check "null-f"     (null? '(1)) #f)
(check "pair-t"     (pair? '(1 2)) #t)
(check "pair-f"     (pair? '()) #f)
(check "list-t"     (list? '(1 2)) #t)
(check "list-f"     (list? (cons 1 2)) #f)
(check "list-nil"   (list? '()) #t)
(check "caar"       (car (car '((1 2) 3))) 1)

; ---------- §5 eq? / equal?（§11 的三个陷阱）----------
(check "eq-nil"     (eq? '() '()) #t)
(check "eq-list"    (eq? '(1) '(1)) #f)
(check "eq-sym"     (eq? 'a 'a) #t)
(check "eq-num"     (eq? 1 1) #t)
(check "eq-bool"    (eq? #t #t) #t)
(check "eq-t1"      (eq? #t 1) #f)
(check "equal-list" (equal? '(1 2 3) (list 1 2 3)) #t)
(check "equal-as"   (equal? 'a "a") #f)
(check "equal-t1"   (equal? #t 1) #f)
(check "equal-nest" (equal? '(1 (2)) '(1 (2))) #t)
(check "equal-float" (equal? 1 1.0) #t)
(check "equal-str"  (equal? "s" "s") #t)
(check "equal-nil"  (equal? '() '()) #t)
(check "equal-pair" (equal? (cons 1 2) (cons 1 2)) #t)
(check "eq-same"    (let ((x '(1 2))) (eq? x x)) #t)

; ---------- §5 谓词 ----------
(check "number-t"   (number? 5) #t)
(check "number-f"   (number? 'x) #f)
(check "number-b"   (number? #t) #f)
(check "boolean-t"  (boolean? #t) #t)
(check "boolean-f"  (boolean? 0) #f)
(check "symbol-t"   (symbol? 'x) #t)
(check "symbol-f"   (symbol? "x") #f)
(check "string-t"   (string? "s") #t)
(check "string-f"   (string? 's) #f)
(check "proc-bi"    (procedure? car) #t)
(check "proc-num"   (procedure? 1) #f)
(check "proc-user"  (procedure? square) #t)
(check "proc-lam"   (procedure? (lambda (x) x)) #t)
(check "zero-t"     (zero? 0) #t)
(check "zero-f"     (zero? 1) #f)
(check "even-t"     (even? 8) #t)
(check "even-f"     (even? 7) #f)
(check "odd-t"      (odd? 7) #t)
(check "odd-f"      (odd? 8) #f)

; ---------- §7 递归：用语言本身定义 map / filter ----------
(define (my-map f xs)
  (if (null? xs) '() (cons (f (car xs)) (my-map f (cdr xs)))))
(check "map"        (my-map (lambda (x) (* x x)) '(1 2 3 4)) '(1 4 9 16))
(check "map-nil"    (my-map car '()) '())
(define (my-filter p xs)
  (cond ((null? xs) '())
        ((p (car xs)) (cons (car xs) (my-filter p (cdr xs))))
        (else (my-filter p (cdr xs)))))
(check "filter"     (my-filter even? '(1 2 3 4 5 6)) '(2 4 6))
(check "filter-all" (my-filter odd? '(2 4)) '())
(define (my-reduce f init xs)
  (if (null? xs) init (my-reduce f (f init (car xs)) (cdr xs))))
(check "reduce"     (my-reduce + 0 '(1 2 3 4)) 10)
(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(check "fact"       (fact 10) 3628800)
(define (fib n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(check "fib"        (fib 15) 610)
(define (sum-to n) (if (= n 0) 0 (+ n (sum-to (- n 1)))))
(check "sum-to"     (sum-to 100) 5050)
(define (deep n) (if (= n 0) 0 (deep (- n 1))))
(check "deep-rec"   (deep 5000) 0)

; ---------- 词法：注释、大小写敏感、转义字符串 ----------
(check "case"       (let ((Foo 1)) Foo) 1)          ; Foo 与 foo 是两个符号
(check "string"     "a\nb" "a\nb")
(check "string-t"   (string? "tab\there") #t)
(check "string-eq"  "quote\"in" "quote\"in")

; ---------- 综合小程序 ----------
(define (compose f g) (lambda (x) (f (g x))))
(check "compose"    ((compose square add5) 0) 25)
(define (range-start start end)
  (if (>= start end) '() (cons start (range-start (+ start 1) end))))
(check "range"      (range-start 1 5) '(1 2 3 4))

(display "selftest done")
(newline)
